use PEDIDOS;

BEGIN TRANSACTION

DELETE FROM TB_ITENSPEDIDO 
WHERE ID_PRODUTO IN 
(
SELECT ID_PRODUTO FROM TB_PRODUTO
WHERE DESCRICAO LIKE '%CANETA%'
)

COMMIT

SELECT * FROM TB_ITENSPEDIDO
WHERE ID_PRODUTO IN 
(
SELECT ID_PRODUTO FROM TB_PRODUTO
WHERE DESCRICAO LIKE '%CANETA%'
)


----------------------------------------------------------------------
BEGIN TRANSACTION

DELETE FROM TB_DEPENDENTE
WHERE CODFUN IN 
(
SELECT CODFUN FROM TB_EMPREGADO
WHERE
(
SELECT COUNT(*)
FROM TB_DEPENDENTE
WHERE NUM_DEPEND BETWEEN 1 AND 3) > 0
)

COMMIT



BEGIN TRANSACTION
DELETE FROM TB_EMPREGADO
WHERE NUM_DEPEND BETWEEN 1 AND 3

COMMIT
----------------------------------------------------------
BEGIN TRANSACTION

SELECT * FROM TB_EMPREGADO
WHERE COD_SUPERVISOR % 2 = 1

UPDATE TB_EMPREGADO
SET SALARIO = SALARIO *1.12
WHERE COD_SUPERVISOR % 2 = 1

SELECT * FROM TB_EMPREGADO
WHERE COD_SUPERVISOR % 2 = 1

COMMIT
-----------------------------------------------------------------------------
BEGIN TRANSACTION
SELECT * FROM TB_EMPREGADO 
WHERE
COD_DEPTO % 2 = 0 AND COD_CARGO % 2 = 0

UPDATE TB_EMPREGADO
SET PREMIO_MENSAL = PREMIO_MENSAL *0.92
WHERE
COD_DEPTO % 2 = 0 AND COD_CARGO % 2 = 0

SELECT * FROM TB_EMPREGADO 
WHERE
COD_DEPTO % 2 = 0 AND COD_CARGO % 2 = 0

COMMIT