USE PEDIDOS


-------- EX. 01 -----------------
/*SELECT TOP 0 * FROM TB_EMPREGADO
SELECT TOP 0 * FROM TB_CARGO*/

SELECT	EMP.NOME,
		CRG.CARGO,
		EMP.SALARIO,
		CRG.SALARIO_INIC,
		EMP.SALARIO - CRG.SALARIO_INIC AS DIFERENCA_SALARIO
FROM	TB_EMPREGADO				   AS EMP 
INNER JOIN TB_CARGO					   AS CRG 
ON CRG.COD_CARGO = EMP.COD_CARGO


-------- EX. 02 -----------------
/*SELECT TOP 0 * FROM TB_EMPREGADO
SELECT TOP 0 * FROM TB_DEPENDENTE*/

SELECT EMP.NOME, 
ISNULL(DEP.NOME, 'NÃO POSSUI DEPENDENTES') AS NOME_DEPENDENTES
FROM TB_EMPREGADO AS EMP
LEFT JOIN TB_DEPENDENTE AS DEP
ON  EMP.CODFUN = DEP.CODFUN


------- EX. 03 -------------------
-- SELECT TOP 0 * FROM TB_EMPREGADO

SELECT EMP.CODFUN, EMP.NOME, EMP.COD_SUPERVISOR,
ISNULL(EMP2.NOME,'NÃO FOI ENCONTRADO SUPERIOR') AS NOME_SUPERVISOR
FROM TB_EMPREGADO AS EMP 
LEFT JOIN TB_EMPREGADO AS EMP2
ON EMP.COD_SUPERVISOR = EMP2.CODFUN

------------ EX. 04 ----------------------
/*SELECT TOP 0* FROM  TB_CLIENTE
SELECT TOP 0* FROM TB_VENDEDOR*/
SELECT PED.NUM_PEDIDO, PED.DATA_EMISSAO, PED.VLR_TOTAL, VEND.NOME AS NOME_VENDEDOR
FROM TB_PEDIDO AS PED
INNER JOIN TB_VENDEDOR AS VEND
ON VEND.CODVEN = PED.CODVEN 

---------- EX. 05 ---------------------------
/*SELECT TOP 0* FROM  TB_CLIENTE
SELECT TOP 0* FROM TB_PEDIDO*/
SELECT PED.NUM_PEDIDO, PED.DATA_EMISSAO, PED.VLR_TOTAL, CLI.NOME AS NOME_CLIENTE
FROM TB_PEDIDO AS PED
INNER JOIN TB_CLIENTE AS CLI
ON CLI.CODCLI = PED.CODCLI 

---------- EX. 06 ---------------------------
/*SELECT TOP 0* FROM  TB_CLIENTE
SELECT TOP 0* FROM TB_PEDIDO
SELECT TOP 0* FROM TB_VENDEDOR*/

SELECT PED.NUM_PEDIDO, PED.DATA_EMISSAO, PED.VLR_TOTAL,CLI.NOME AS NOME_CLIENTE,  VEND.NOME AS NOME_VENDEDOR
FROM TB_PEDIDO AS PED 
INNER JOIN TB_CLIENTE AS CLI
ON CLI.CODCLI = PED.CODCLI 
INNER JOIN TB_VENDEDOR AS VEND
ON VEND.CODVEN = PED.CODVEN 

---------- EX. 07 ---------------------------
/*SELECT TOP 0* FROM TB_CARGO
SELECT TOP 0* FROM TB_EMPREGADO*/

SELECT CRG.CARGO AS CARGOS_SEM_FUNC, EMP.NOME AS FUNCIONARIOS_SEM_CARGO
FROM TB_CARGO AS CRG 
FULL OUTER JOIN TB_EMPREGADO AS EMP
ON CRG.COD_CARGO = EMP.COD_CARGO 
WHERE EMP.COD_CARGO IS NULL OR CRG.COD_CARGO IS NULL

---------- EX. 08 ---------------------------
/*SELECT TOP 0* FROM TB_PEDIDO
SELECT TOP 0* FROM TB_ITENSPEDIDO
SELECT TOP 0* FROM TB_PRODUTO
SELECT TOP 0* FROM TB_COR*/
SELECT	PED.NUM_PEDIDO, 
		ITN.ID_PRODUTO,
		ITN.QUANTIDADE,
		PROD.COD_PRODUTO,
		PROD.DESCRICAO
FROM TB_PEDIDO AS PED
INNER JOIN TB_ITENSPEDIDO AS ITN ON ITN.NUM_PEDIDO = PED.NUM_PEDIDO
INNER JOIN TB_PRODUTO AS PROD ON PROD.COD_PRODUTO = ITN.COD_PRODUTO
INNER JOIN TB_COR AS COR ON COR.CODCOR = ITN.CODCOR
WHERE (COR.COR = 'BRANCO' OR COR.COR = 'LARANJA') AND YEAR(PED.DATA_EMISSAO) BETWEEN 2012 AND 2013;