use PEDIDOS

-- 1--   
SELECT NOME   
FROM   TB_CLIENTE
WHERE LEN(SUBSTRING(NOME, 1, CHARINDEX(' ', NOME + ' ') - 1)) > 5
  AND SUBSTRING(NOME, 1, 1) IN ('A', 'E', 'I', 'O', 'U');

-- 2 --
SELECT TOP 4 NOME,
			 CIDADE
FROM TB_CLIENTE
WHERE RIGHT(NOME, 1) = 'I'
AND LEN(CIDADE) > 10

-- 3 --
SELECT UPPER(LEFT(NOME, 1)) + 
	   UPPER(RIGHT(NOME, 1)) AS CONCATENA
FROM TB_EMPREGADO

-- 4 --
SELECT
    CASE WHEN CHARINDEX('Av.', ENDERECO) > 0 
	THEN REPLACE(ENDERECO, 'Av.', 'Avenida ')  
	ELSE Endereco END 
from TB_CLIENTE

-- 5 --
SELECT ENDERECO
FROM TB_CLIENTE
WHERE ENDERECO LIKE '% DA %'

-- 6 --
SELECT
    ENDERECO,
    CONCAT(
        LEFT(ENDERECO, CHARINDEX(' DA ', ENDERECO + ' DA ') - 1),
        ' ',
        RIGHT(ENDERECO, LEN(ENDERECO) - CHARINDEX(' DA ', ENDERECO + ' DA ') - 2)
    ) AS ENDERECO_MODIFICADO
FROM
    TB_CLIENTE
WHERE
    CHARINDEX(' DA ', ENDERECO) > 0;

-- 7 --
SELECT TOP 50
    CNPJ,
    CONCAT(
        SUBSTRING(CNPJ, 1, 2), '.',        
        SUBSTRING(CNPJ, 3, 3), '.',        
        SUBSTRING(CNPJ, 6, 3), '/',        
        SUBSTRING(CNPJ, 9, 4), '-',        
        SUBSTRING(CNPJ, 13, 2)             
    )
FROM
    TB_CLIENTE
WHERE
    LEN(REPLACE(CNPJ, ' ', '')) = 14

-- 8 --
SELECT
    DESCRICAO + ': ' + CAST(PRECO_VENDA - PRECO_CUSTO AS VARCHAR(20)) AS LUCRO_TOTAL
FROM
    TB_PRODUTO;

-- 9 ---
SELECT 
    TB_CLIENTE.NOME,
	TB_PEDIDO.NUM_PEDIDO  
FROM
    TB_CLIENTE
INNER JOIN
    TB_PEDIDO  ON TB_PEDIDO.CODCLI = TB_CLIENTE.CODCLI
WHERE
    TB_CLIENTE.ESTADO IN ('SP', 'RJ', 'MG', 'ES')
ORDER BY
TB_CLIENTE.NOME
 
-- 10 --
SELECT
    CLI.NOME AS NOME_CLIENTE,
    COUNT(PED.NUM_PEDIDO) AS QTDE_VENDIDA,
    SUM(PED.VLR_TOTAL) AS VALOR_TOTAL_VENDAS
FROM
    TB_PEDIDO AS PED
JOIN
    TB_CLIENTE AS CLI  ON CLI.CODCLI = PED.CODCLI
WHERE
    CLI.ESTADO IN ('SP', 'RJ', 'MG', 'ES')
GROUP BY
    CLI.NOME
ORDER BY
    QTDE_VENDIDA DESC;